{% set name = "ihm" %}
{% set version = "2.12" %}


package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/ihm-{{ version }}.tar.gz
  sha256: 1172cb95007d02dd32fdfde257806d43f63f976ddec9ffaa78265ff9e244f3ec
  patches:
    - ihm-limited-api.patch

build:
  number: 0
  python_version_independent: true   # [is_abi3]
  script: {{ PYTHON }} -m pip install . -vv
  skip: True                         # [is_abi3 and not is_python_min]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python-abi3                    # [is_abi3]
    - pip
    - python
    - setuptools
  run:
    - python
    # msgpack needed for BinaryCIF support
    - msgpack-python

test:
  imports:
    - ihm
  commands:
    - pip check
    - abi3audit $SP_DIR/ihm/_format.abi3.so -s -v --assume-minimum-abi3 {{ python_min }}   # [unix and is_abi3]
    - abi3audit %SP_DIR%/ihm/_format.pyd -s -v --assume-minimum-abi3 {{ python_min }}      # [win and is_abi3]
  requires:
    - pip
    - abi3audit                      # [is_abi3]

about:
  home: https://github.com/ihmwg/python-ihm
  summary: Package for handling IHM mmCIF and BinaryCIF files
  license: MIT
  license_file: LICENSE
  description: |
    This is a Python package to assist in handling mmCIF
    (http://mmcif.wwpdb.org/) and BinaryCIF
    (https://github.com/molstar/BinaryCIF) files compliant with the
    integrative/hybrid modeling (IHM) extension
    (http://mmcif.wwpdb.org/dictionaries/mmcif_ihm.dic/Index/).
    It works with Python 3.6 or later.

    Please see the documentation at https://python-ihm.readthedocs.org/
    or some worked examples at
    https://github.com/ihmwg/python-ihm/tree/main/examples
    for more details.
  doc_url: https://python-ihm.readthedocs.io/
  dev_url: https://github.com/ihmwg/python-ihm

extra:
  recipe-maintainers:
    - benmwebb
