{% set name = "ihm" %}
{% set version = "1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ihm-{{ version }}.tar.gz
  sha256: 6608897b60ae4986ad98328756781e080818d651448570748712d4c5ae4a4a98

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - python
    # msgpack needed for BinaryCIF support
    - msgpack-python

test:
  imports:
    - ihm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ihmwg/python-ihm
  summary: Package for handling IHM mmCIF and BinaryCIF files
  license: MIT
  license_file: LICENSE
  description: |
    This is a Python package to assist in handling mmCIF
    (http://mmcif.wwpdb.org/) and BinaryCIF
    (https://github.com/dsehnal/BinaryCIF) files compliant with the
    integrative/hybrid modeling (IHM) extension
    (http://mmcif.wwpdb.org/dictionaries/mmcif_ihm.dic/Index/).
    It works with Python 2.7 or Python 3.

    Please see the documentation at https://python-ihm.readthedocs.org/
    or some worked examples at
    https://github.com/ihmwg/python-ihm/tree/main/examples
    for more details.
  doc_url: https://python-ihm.readthedocs.io/
  dev_url: https://github.com/ihmwg/python-ihm

extra:
  recipe-maintainers:
    - benmwebb
